version: '3'
services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=platform
      - POSTGRES_PASSWORD=platform
      - POSTGRES_DB=platform
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  api:
    build: ./api
    restart: always
    ports:
      - 3000:3000
    links:
      - database
    environment:
      - DB_URI=postgres://platform:platform@database/platform
      - NODE_ENV=production
      - SECRET=wowthisismysecret
  app:
    build: ./app
    restart: always
    ports:
      - 8080:8080
